version = 0.1

[default.build.parameters]
cached = true
parallel = true

[default.validate.parameters]
lint = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"

[default.deploy.parameters]
stack_name = "treuepunkte-iac-staging"
resolve_s3 = true
s3_prefix = "treuepunkte-iac-staging"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "AppEnv=\"staging\" DbPort=\"3306\" DbName=\"treuepunkte\" DbMasterUsername=\"admin\" VpcCidr=\"10.0.0.0/16\" PublicSubnet1Cidr=\"10.0.1.0/24\" PublicSubnet2Cidr=\"10.0.2.0/24\" PrivateSubnet1Cidr=\"10.0.11.0/24\" PrivateSubnet2Cidr=\"10.0.12.0/24\""
image_repositories = []

[default.global.parameters]
region = "eu-west-1"

[production.global.parameters]
stack_name = "treuepunkte-iac-production"
region = "eu-west-1"

[production.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
s3_prefix = "treuepunkte-iac-production"
parameter_overrides = "AppEnv=\"production\" DbPort=\"3306\" DbName=\"treuepunkte_prod\" DbMasterUsername=\"admin\" VpcCidr=\"10.1.0.0/16\" PublicSubnet1Cidr=\"10.1.1.0/24\" PublicSubnet2Cidr=\"10.1.2.0/24\" PrivateSubnet1Cidr=\"10.1.11.0/24\" PrivateSubnet2Cidr=\"10.1.12.0/24\""
image_repositories = []


[staging.deploy.parameters]
stack_name = "treuepunkte-iac-staging"
resolve_s3 = true
s3_prefix = "treuepunkte-iac-staging"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "AppEnv=\"staging\" DbPort=\"3306\" DbName=\"treuepunkte\" DbMasterUsername=\"admin\" VpcCidr=\"10.0.0.0/16\" PublicSubnet1Cidr=\"10.0.1.0/24\" PublicSubnet2Cidr=\"10.0.2.0/24\" PrivateSubnet1Cidr=\"10.0.11.0/24\" PrivateSubnet2Cidr=\"10.0.12.0/24\""
image_repositories = []

[staging.global.parameters]
region = "eu-west-1"
