name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'

      - name: Set up AWS SAM CLI
        uses: aws-actions/setup-sam@v2

      - name: Run tests
        run: make test

      - name: Validate SAM template
        run: make validate

      - name: Build SAM application
        run: make build
